version: '2'
services:
  app:
    build: app
    environment:
      - VIRTUAL_HOST=fastly-app.namiking.net
  static:
    build: static
    volumes:
      - ./static/public:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=fastly-static.namiking.net
