version: '2'
services:
  web:
    build: web
    environment:
      - VIRTUAL_HOST=fastly-web.namiking.net
  static:
    build: static
    volumes:
      - ./static/html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=fastly-static.namiking.net
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '1234:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
      - static
